version: '5.11'
services:
  neo4j:
    image: neo4j:5.11.0-enterprise
    ports:
      - 7474:7474
      - 7687:7687
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/bcmx2781
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    volumes:
      - ./db/data:/data
      - ./db/conf:/conf
      - ./db/logs:/logs
      - ./db/plugins:/plugins